name: continuous-deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy to server Nginx
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v2
      env:
        remote_path: /var/www/deployNginx
        remote_host: "${{ secrets.HOST_DNS }}" 
        remote_user: "${{ secrets.USERNAME }}"
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
