name: continuous-deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v1

    - name: Hugo build
      run: |
        sudo snap install hugo --channel=extended
        hugo 
      
    - name: SSH Setup
      env:
        remote_host: "${{ secrets.HOST_DNS }}" 
        remote_user: "${{ secrets.USERNAME }}"
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
      run: |
         echo test, and deploy your project.

    - name: Rsync deployment
      run: |
                rsync -avz -e ssh --delete public/ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/www/